# Local target directory serving as the root of the repository structure
target: ./target/

# true: copy all repositories into the target root
# false: create directory structure using the git server groups
flatten: false

# clone: Runs git clone with --mirror flag on the repositry, cloning all branches tags and notes
# mirror: Only runs git clone --recursive on the repository, copying the main branch
method: mirror

# List if URL-s to the repositories to save
repositories:
  - https://gitlab.com/richardnagy/git-repository-auto-backup
  - https://gitlab.com/richardnagy/webprojects/3d-ray-casting
  - https://gitlab.com/richardnagy/webprojects/webgl-fractals
  - https://gitlab.com/richardnagy/webprojects/word-salad
  - https://gitlab.com/richardnagy/webprojects/trigonometric-convex-hull
  - https://gitlab.com/richardnagy/security/spy-proxy
  - https://gitlab.com/richardnagy/security/passphrase-password-vault
  - https://gitlab.com/richardnagy/security/browser-fingerprint
  - https://gitlab.com/richardnagy/security/passhash