# Local target directory serving as the root of the repository structure
# (default) ./target/
target: ./target/

# true: copy all repositories into the target root
# false: (default) create directory structure using the git server subgroups
flatten: false

# mirror: (default) Runs git clone with --mirror flag on the repositry, cloning all branches tags, and notes from origin
# clone: Only runs git clone --recursive on the repository, copying the main branch from origin
method: mirror

# List of URL-s to the repositories
repositories:
  - https://gitlab.com/richardnagy/container-environments/gradle-java-testing-docker-environment
  - https://gitlab.com/richardnagy/research/refactoring-legacy-publication
  - https://gitlab.com/richardnagy/git-repository-auto-backup
  - https://gitlab.com/richardnagy/webprojects/webrtc-data-channel-between-client-and-server
  - https://gitlab.com/richardnagy/webprojects/3d-ray-casting
  - https://gitlab.com/richardnagy/webprojects/webgl-fractals
  - https://gitlab.com/richardnagy/webprojects/word-salad
  - https://gitlab.com/richardnagy/webprojects/trigonometric-convex-hull
  - https://gitlab.com/richardnagy/security/spy-proxy
  - https://gitlab.com/richardnagy/security/passphrase-password-vault
  - https://gitlab.com/richardnagy/security/browser-fingerprint
  - https://gitlab.com/richardnagy/security/passhash
  - https://gitlab.com/richardnagy/git-repository-auto-backup
  - https://gitlab.com/richardnagy/shopify-bulk-product-uploader